### ISSUE TITLE
Is there a way to cut down the amount of divs Vue creates?

### ISSUE THREAD

**Issue by NetOperatorWibby** [lbryio/lbry.tech#34]
![ss 2018-05-03 at 4 39 31 pm](https://user-images.githubusercontent.com/1288356/39604199-bc32441c-4ef0-11e8-90b3-fa81c7b5c3bc.png)

Five of these `div`s are unnecessary and mess up what used to be simple `flex` CSS stuff. Two `id`s of the same name isn't valid HTML but I don't know if that matters here.

**Comment by NetOperatorWibby** [comment]
With a page layout like this:

```html
<!DOCTYPE html>
<html lang="en">
  <head/>

  <body>
    <header/>
    <main/>
    <footer/>
  </body>
</html>
```

This CSS would make it so `<main>` would be full height.

```css
html,
body {
  width: 100%; height: 100%;
}

body {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

main {
  flex: 1;
}
```

Instead of looking like this, with extra white space at the bottom:

![ss 2018-05-03 at 4 52 58 pm](https://user-images.githubusercontent.com/1288356/39604603-80124430-4ef2-11e8-9bf1-febb78476b4d.png)

I can code around it (obviously), it just wouldn't look good (the code).
